### ISSUE TITLE
cache.zw3rk.com corrupted

### ISSUE THREAD

**Issue by minolinpwork** [input-output-hk/devx#122]
Getting an error whilst trying to access cache cache.zw3rk.com used in flake.nix - not sure who to log this error with?

**curl https://cache.zw3rk.com/**

<?xml version="1.0" encoding="UTF-8"?>
<Error>
	<Code>InternalError</Code>
	<Message>We encountered an internal error, please try again.: cause(corrupted backend format, specified drive mount has unexpected previous content)</Message>
	<Key>index.html</Key>
	<BucketName>nix-cache</BucketName>
	<Resource>/nix-cache/index.html</Resource>
	<Region>us-east-1</Region>
	<RequestId>17AF08317BAA9910</RequestId>
	<HostId>e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855</HostId>
</Error>

**Comment by yvan-sraka** [comment]
You should remove cache.zw3rk.com, where still in use. http://cache.iog.io should have everything you need!

**Comment by minolinpwork** [comment]
This is in your [flake.nix](https://github.com/input-output-hk/devx/blob/main/flake.nix) which I'm assuming is causing an issue when trying to build eg.
nix develop github:input-output-hk/devx#ghc810 --no-write-lock-file --refresh --system x86_64-linux

**Comment by yvan-sraka** [comment]
`cache.zw3rk.com` should now work as expected, can you confirm?

**Comment by minolinpwork** [comment]
Confirmed, it is working.
