### ISSUE TITLE
Missing `-iog-full` devx container

### ISSUE THREAD

**Issue by sgillespie** [input-output-hk/devx#136]
IOG Full flavor was added with #129, which also removed postgresql from the IOG flavor. This has resulted in the following error in [cardano-db-sync](https://github.com/IntersectMBO/cardano-db-sync/):

```
[_13] trying: postgresql-libpq-0.10.0.0 (dependency of postgresql-simple)
[_14] rejecting: postgresql-libpq:-use-pkg-config (constraint from config
file, command line flag, or user target requires opposite flag selection)
[_14] rejecting: postgresql-libpq:+use-pkg-config (conflict: pkg-config
package libpq>=10.22, not found in the pkg-config database)
[_14] fail (backjumping, conflict set: postgresql-libpq,
postgresql-libpq:use-pkg-config)
```

Simply updating the [devx action](https://github.com/input-output-hk/actions/tree/latest/devx) will not work yet, until the devx container is added to ghcr.io

**Comment by sgillespie** [comment]
Further complicating things, [this github workflow](https://github.com/input-output-hk/devx/blob/main/.github/workflows/build-and-test.yml#L42) depends on the devx action. This means that I can't update devx until after I've updated the devx action, and vice versa

**Comment by yvan-sraka** [comment]
As a _quick late-Friday fix_, I can re-add `postgresql` to the `-iog`-flavor, and then work out a proper way to propagate those changes next week. Sorry for the inconvenience :/
