### ISSUE TITLE
Support more GHC versions?

### ISSUE THREAD

**Issue by yvan-sraka** [input-output-hk/devx#23]
Do we agree on the only 3 GHC versions currently offered by `input-output-hk/devx` are only `ghc8107`, `ghc902`, and `ghc925`?

That’s the only 3 versions that show up when I inspect `devShell.x86_64-linux` on
```
nix repl --extra-experimental-features 'flakes repl-flake' 'github:input-output-hk/devx'
```

**Comment by angerman** [comment]
We support 810, 90, 92, 94, and 96. So I guess we can close this. the devx shell will try to always support the latest of the last few compilers. We'll drop 8.10 once IOG drops it.
